# Generated by Django 5.0.2 on 2024-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_dislikes_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='post_images/', verbose_name='Мініатюра'),
        ),
    ]
